format = """
$username\
$hostname\
$kubernetes\
$aws\
$line_break\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$docker_context\
$line_break\
$python\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "blue"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"

[git_status]
style = "cyan"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
style = "bright-cyan"
